name: "projeto_final_bd2"
services:
  db:
    build:
        context: .
        dockerfile: Dockerfile.db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    volumes:
      - database_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/ --quiet
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "27019:27017"

  web:
    build:
        context: .
        dockerfile: Dockerfile.web
    command: bash -c "python initialize_db.py -f True && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: no
    environment:
      - DB_HOST=db
      - DB_NAME=bd2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - MONGO_DB_CONNECTION=mongodb://root:root@mongo:27017/?retryWrites=true&w=majority

    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

volumes:
  database:
  database_mongo:

