services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python initialize_db.py -f True && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: no
    environment:
      - DB_HOST=db
      - DB_NAME=bd2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

    depends_on:
      db:
        condition: service_healthy

volumes:
  database:

