services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bd2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - "5444:5432"
  web:
    build: .
    command: bash -c "python initialize_db.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: no
    environment:
      - DB_HOST=db
      - DB_NAME=bd2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

    depends_on:
      - db
